@startuml

component Device <<device>> {
    component Sensor <<device>>
    component Process <<schedule>>
    component Driver as "Sensor" <<driver>>
    component ClientMQ <<client>>
}

Process -left-> Driver : **1.1** get data
Driver -up-> Sensor : **1.2** read data
Process -up-> ClientMQ : **1.3** write data

component Server <<device>> {
    component Queue as "Eclipse Mosquitto\nopen source MQTT broker" <<service>>
    component Tiles as "Node v16\nQuasar framework" <<service>>
}

ClientMQ --> Queue : **1.4** publish data\nMQTT port 1883 \nor websoket port 9001

component browser <<client>> {
    component TilesUI as "MQTT Tiles\ndashboard visualization tool" <<Web Application>>
}

Tiles -right-> TilesUI : **2.1** load dashboard\nhttp port 8080
TilesUI --> Queue : **2.3** get data\nwebsocket port 9001

actor User

TilesUI <-right- User : **2.2** use dashboard


@enduml

